language:
    - cpp
    - java

os:
    - linux
    - osx

before_install:
    - sudo apt-get install cmake
    - git submodule update

install:
    - mvn

script:
    - javac -cp "target/*.jar" examples/Test.java
    - cat examples/example | java -cp "target/*.jar:examples" Test --segment-model=ltp_data/cws.model --postag-model=ltp_data/pos.model --ner-model=ltp_data/ner.model --parser-model=ltp_data/parser.model --srl-dir=ltp_data/srl/
