language:
    - cpp
    - java

os:
    - linux
    - osx

before_install:
    - sudo apt-get install cmake
    - git submodule update

install:
    - cmake -DLTP_HOME=ltp/ .
    - make
    - ant
    - export LD_LIBRARY_PATH=LD_LIBRARY_PATH:`pwd`/libs/:`pwd`/ltp/lib

script:
    - javac -cp "output/jar/ltp4j.jar" examples/Test.java
    - java -cp "output/jar/ltp4j.jar:examples" Test -h
