language:
    - cpp
    - java

os:
    - linux
    - osx

before_install:
    - sudo apt-get install cmake
    - git submodule update
    - cd ltp
    - ./configure
    - make
    - cd ..

install:
    - cmake -DLTP_HOME=`pwd`/ltp/ .
    - make
    - ant
    - export LD_LIBRARY_PATH=LD_LIBRARY_PATH:`pwd`/libs/:`pwd`/ltp/lib

script:
    - javac -cp "output/jar/ltp4j.jar" examples/Test.java
    - echo "中国进出口银行与中国银行加强合作" | java -cp "output/jar/ltp4j.jar:examples" Test --segment-model=ltp_data/cws.model --postag-model=ltp_data/pos.model --ner-model=ltp_data/ner.model --parser-model=ltp_data/parser.model --srl-dir=ltp_data/srl/
